### ISSUE TITLE
カテゴリの管理画面の新規追加が動作しない

### ISSUE THREAD

**Issue by smellman** [appirits/comable#7]
カテゴリの管理画面において、新規追加ボタンが動かない
backend/app/views/comable/admin/categories/index.slim
コードを見ると単純にリンクになっています

**Comment by hyoshida** [comment]
ご報告ありがとうございます！

JavaScript部分なのでコンソール上でエラーになっている可能性がありますね。
いま手元の環境ではとくにエラーなく動作するので環境依存の問題があるのかもしれません。

ブラウザの開発者ツールなどから発生しているエラーメッセージを取得することは可能でしょうか。

**Comment by smellman** [comment]
https://github.com/appirits/comable/blob/master/backend/app/views/comable/admin/categories/index.slim#L84
このコードだと
javascript:create_new_node()
に画面遷移しちゃうっていう問題です。
javascript自体は動きますが、画面遷移しちゃうので空っぽの画面が表示される。
他のコードと同様に href='javascript:void(0)' でonclickでjavascript叩くか、
https://github.com/appirits/comable/blob/master/backend/app/views/comable/admin/categories/index.slim#L52
この後にreturn false; 追加するかのどっちかでいいかなと思った

**Comment by smellman** [comment]
onclickじゃないとだめだった。return false;を使う方も画面遷移してfalseって出てくる。

**Comment by hyoshida** [comment]
プルリクまでありがとうございます！

Chrome では現状のコードでも問題なく動作するようですが、確かに他のブラウザだと `href ="javascript:create_new_node()"` では画面遷移として処理されるかもですね。

後ほど他のブラウザでの動作も含めて検証してみます。

**Comment by hyoshida** [comment]
Firefox と IE で問題が再現することを確認しました。
プルリク、マージします。
@smellman さんありがとうございます！
